version: '3.9'

services:
  edge:
    image: nginx:1.23.3
    container_name: edge
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  api:
    image: nginx:1.23.3
    container_name: api
    volumes:
      - ./services/api/nginx.conf:/etc/nginx/conf.d/default.conf

  web:
    image: nginx:1.23.3
    container_name: web
    volumes:
      - ./services/web/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./services/web/index.html:/var/www/html/web/index.html
