version: '3.9'

services:
  edge:
    build: .
    container_name: edge
    ports:
      - "80:80"

  api:
    image: nginx:1.23.2
    container_name: api
    volumes:
      - ./services/api/api.conf:/etc/nginx/conf.d/default.conf

  web:
    image: nginx:1.23.1
    container_name: web
    volumes:
      - ./services/web/web.conf:/etc/nginx/conf.d/default.conf
      - ./services/web/index.html:/var/www/html/web/index.html
